services:
  excalidraw:
    build:
      context: .
      args:
        NODE_ENV: production
        VITE_APP_WS_SERVER_URL: ""
        VITE_APP_STORAGE_BACKEND_URL: ""
        VITE_APP_FILE_UPLOAD_URL: "http://school.rocpow.com:9081"
        VITE_APP_FILE_UPLOAD_PATH: "/function/oss/upload/single/file"
        VITE_APP_FILE_UPLOAD_CODE: "default"
        VITE_APP_FILE_UPLOAD_ASSET_PREFIX: "http://school.rocpow.com:9000"
    ports:
      - "13000:80"
    restart: unless-stopped
    depends_on:
      storage-api:
        condition: service_started
      collab:
        condition: service_started

  storage-api:
    build:
      context: ./selfhosted-storage-api
    restart: unless-stopped
    environment:
      PORT: 3015
      API_PREFIX: /api/v1
      CORS_ORIGIN: "*"
      STORAGE_DIR: /data
    volumes:
      - ./data/storage:/data

  collab:
    build:
      context: .
      dockerfile: collab/Dockerfile
    restart: unless-stopped
